[package]
name = "constant_product_amm"
version = "0.1.0"

[dependencies]
starknet = "2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }

[[target.starknet-contract]]
