[default]
extend-ignore-identifiers-re = ["requestor", "REQUESTOR", "Requestor", "groth", "Groth"]

[type.po]
extend-glob = ["*.po", "*.css", "*.js"]
check-file = false

[files]
extend-exclude = ["po/*.po", "listings/**/*.json"]
