name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    # The --locked flag is important for reproducible builds.
    - name: Install mdbook
      run: cargo install mdbook --locked --version 0.4.35
      shell: bash

    - name: Install mdbook-last-changed
      run: cargo install mdbook-last-changed --locked --version 0.1.4
      shell: bash
