[package]
name = "advanced_factory"
version.workspace = true
edition = "2024_07"

[dependencies]
starknet.workspace = true
components.workspace = true
snforge_std.workspace = true
crowdfunding = { path = "../crowdfunding" }

[dev-dependencies]
assert_macros.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
casm = true
build-external-contracts = ["crowdfunding::campaign::Campaign"]
