[package]
name = "advanced_factory"
version.workspace = true
edition = "2023_11"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
components.workspace = true
alexandria_storage.workspace = true
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
casm = true