[package]
name = "nft_dutch_auction"
version.workspace = true
edition = '2023_11'

[dependencies]
erc20 = { path = "../erc20" }
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
build-external-contracts = ["erc20::token::erc20"]
