name: Verify Cairo programs compilation

description: Verify if all Cairo programs extracted from markdown can be compiled.

runs:
  using: composite
  steps:
    - name: Install scarb
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: "2.3.0"

    - name: Run build script
      shell: bash
      run: |
        chmod +x scripts/cairo_programs_verifier.sh
        ./scripts/cairo_programs_verifier.sh
