[package]
name = "simple_account"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_account.workspace = true
openzeppelin_introspection.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
