[package]
name = "simple_account"
version.workspace = true
edition = '2023_11'


[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
