[package]
name = "using_lists"
version.workspace = true
edition = '2023_10'

[dependencies]
starknet.workspace = true
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git",  rev="ae1d514"}

[scripts]
test.workspace = true

[[target.starknet-contract]]
