[package]
name = "erc20"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
