[package]
name = "erc20"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
